# Generated by Django 4.2.6 on 2023-11-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
